name: Helm

on:
  push:
    tags:
    - '*'

jobs:
  helm-build:
    name: Helm Build
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: release_name
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Checkout tag
      uses: actions/checkout@v2
      with:
        path: ${{ steps.release_name.outputs.VERSION }}
        ref: ${{ steps.release_name.outputs.VERSION }}

    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: gh-pages
        ref: gh-pages

    - name: Build chart repo
      run: |
        mkdir -p ${{ steps.release_name.outputs.VERSION }}/artifacts
        cd ${{ steps.release_name.outputs.VERSION }}/artifacts
        sed -i "s#tag: latest#tag: ${{ steps.release_name.outputs.VERSION }}#g" ../build/helm/dynratelimiter-operator/values.yaml
        sed -i "s#ersion: latest#ersion: ${{ steps.release_name.outputs.VERSION }}#g" ../build/helm/dynratelimiter-operator/Chart.yaml
        sed -i "s#ersion: v#ersion: #g" ../build/helm/dynratelimiter-operator/Chart.yaml
        helm package ../build/helm/dynratelimiter-operator
        mv * ../../gh-pages/
        cd ../../gh-pages
        helm repo index . --url https://arivum.github.io/dynratelimiter
        cp ../${{ steps.release_name.outputs.VERSION }}/README.md .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update helm registry"
        git push