name: Go

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: release_name
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.release_name.outputs.VERSION }}
        release_name: Release ${{ steps.release_name.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Publish go module
      run: go list -m github.com/arivum/resource-ticker@${{ steps.release_name.outputs.VERSION }}
